services:
  - type: web
    name: Incidencias
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=10000 --server.enableCORS=false
    envVars:
  - key: SUPABASE_URL
    value: postgresql://postgres:miNuevaClave123@db.onrmliubiwqfczmmezzj.supabase.co:6543/postgres
