services:
  - type: web
    name: incidencias-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=10000 --server.enableCORS=false
    envVars:
      - key: SUPABASE_URL
        value: postgresql://postgres:dkZKG77K.@db.onrmliubiwqfczmmezzj.supabase.co:5432/postgres
