services:
  - type: web
    name: Incidencias
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=10000 --server.enableCORS=false
    envVars:
      - key: SUPABASE_URL
        value: postgresql://postgres:dkZKG77K.@aws-0-eu-west-3.pooler.supabase.com:6543/postgres
